# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(606, 865)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.sistem = QtWidgets.QLabel(self.centralwidget)
        self.sistem.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sistem.setFont(font)
        self.sistem.setAlignment(QtCore.Qt.AlignCenter)
        self.sistem.setObjectName("sistem")
        self.verticalLayout_3.addWidget(self.sistem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ac_kapat_buton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ac_kapat_buton.setFont(font)
        self.ac_kapat_buton.setObjectName("ac_kapat_buton")
        self.horizontalLayout_2.addWidget(self.ac_kapat_buton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.giris = QtWidgets.QLabel(self.centralwidget)
        self.giris.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.giris.setFont(font)
        self.giris.setAlignment(QtCore.Qt.AlignCenter)
        self.giris.setObjectName("giris")
        self.verticalLayout_7.addWidget(self.giris)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.giris_ac_buton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.giris_ac_buton.setFont(font)
        self.giris_ac_buton.setObjectName("giris_ac_buton")
        self.horizontalLayout_6.addWidget(self.giris_ac_buton)
        self.giris_kapat_buton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.giris_kapat_buton.setFont(font)
        self.giris_kapat_buton.setObjectName("giris_kapat_buton")
        self.horizontalLayout_6.addWidget(self.giris_kapat_buton)
        self.verticalLayout_7.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_4.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.cikis = QtWidgets.QLabel(self.centralwidget)
        self.cikis.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cikis.setFont(font)
        self.cikis.setAlignment(QtCore.Qt.AlignCenter)
        self.cikis.setObjectName("cikis")
        self.verticalLayout_8.addWidget(self.cikis)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.cikis_ac_buton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cikis_ac_buton.setFont(font)
        self.cikis_ac_buton.setObjectName("cikis_ac_buton")
        self.horizontalLayout_5.addWidget(self.cikis_ac_buton)
        self.cikis_kapat_buton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cikis_kapat_buton.setFont(font)
        self.cikis_kapat_buton.setObjectName("cikis_kapat_buton")
        self.horizontalLayout_5.addWidget(self.cikis_kapat_buton)
        self.verticalLayout_8.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4.addLayout(self.verticalLayout_8)
        self.gridLayout.addLayout(self.horizontalLayout_4, 0, 0, 1, 3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.ucretli_buton = QtWidgets.QRadioButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ucretli_buton.setFont(font)
        self.ucretli_buton.setObjectName("ucretli_buton")
        self.verticalLayout_4.addWidget(self.ucretli_buton)
        self.ucretsiz_buton = QtWidgets.QRadioButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ucretsiz_buton.setFont(font)
        self.ucretsiz_buton.setObjectName("ucretsiz_buton")
        self.verticalLayout_4.addWidget(self.ucretsiz_buton)
        self.gridLayout.addLayout(self.verticalLayout_4, 1, 0, 1, 1)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.doluluk = QtWidgets.QLabel(self.centralwidget)
        self.doluluk.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.doluluk.setFont(font)
        self.doluluk.setAlignment(QtCore.Qt.AlignCenter)
        self.doluluk.setObjectName("doluluk")
        self.verticalLayout_6.addWidget(self.doluluk)
        self.doluluk_progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.doluluk_progressBar.setMinimumSize(QtCore.QSize(50, 70))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.doluluk_progressBar.setFont(font)
        self.doluluk_progressBar.setProperty("value", 24)
        self.doluluk_progressBar.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.doluluk_progressBar.setTextVisible(False)
        self.doluluk_progressBar.setObjectName("doluluk_progressBar")
        self.verticalLayout_6.addWidget(self.doluluk_progressBar)
        self.gridLayout.addLayout(self.verticalLayout_6, 1, 1, 2, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.arac_sayisi = QtWidgets.QLabel(self.centralwidget)
        self.arac_sayisi.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.arac_sayisi.setFont(font)
        self.arac_sayisi.setAlignment(QtCore.Qt.AlignCenter)
        self.arac_sayisi.setObjectName("arac_sayisi")
        self.verticalLayout_5.addWidget(self.arac_sayisi)
        self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lcdNumber.setFont(font)
        self.lcdNumber.setDigitCount(1)
        self.lcdNumber.setObjectName("lcdNumber")
        self.verticalLayout_5.addWidget(self.lcdNumber)
        self.gridLayout.addLayout(self.verticalLayout_5, 1, 2, 2, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.ucret = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ucret.setFont(font)
        self.ucret.setAlignment(QtCore.Qt.AlignCenter)
        self.ucret.setObjectName("ucret")
        self.verticalLayout_2.addWidget(self.ucret)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.ucret_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ucret_lineEdit.setFont(font)
        self.ucret_lineEdit.setObjectName("ucret_lineEdit")
        self.horizontalLayout_3.addWidget(self.ucret_lineEdit)
        self.guncelle_buton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.guncelle_buton.setFont(font)
        self.guncelle_buton.setObjectName("guncelle_buton")
        self.horizontalLayout_3.addWidget(self.guncelle_buton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.gridLayout.addLayout(self.verticalLayout_2, 2, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.plaka_textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.plaka_textEdit.setObjectName("plaka_textEdit")
        self.verticalLayout.addWidget(self.plaka_textEdit)
        self.gridLayout.addLayout(self.verticalLayout, 3, 0, 1, 3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.plaka = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.plaka.setFont(font)
        self.plaka.setObjectName("plaka")
        self.horizontalLayout.addWidget(self.plaka)
        self.plaka_ekle_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.plaka_ekle_lineEdit.setFont(font)
        self.plaka_ekle_lineEdit.setObjectName("plaka_ekle_lineEdit")
        self.horizontalLayout.addWidget(self.plaka_ekle_lineEdit)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.gridLayout.addLayout(self.horizontalLayout, 4, 0, 1, 3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 606, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.sistem.setText(_translate("MainWindow", "Sistem"))
        self.ac_kapat_buton.setText(_translate("MainWindow", "Aç/Kapat"))
        self.giris.setText(_translate("MainWindow", "Giriş"))
        self.giris_ac_buton.setText(_translate("MainWindow", "Aç"))
        self.giris_kapat_buton.setText(_translate("MainWindow", "Kapat"))
        self.cikis.setText(_translate("MainWindow", "Çıkış"))
        self.cikis_ac_buton.setText(_translate("MainWindow", "Aç"))
        self.cikis_kapat_buton.setText(_translate("MainWindow", "Kapat"))
        self.ucretli_buton.setText(_translate("MainWindow", "Ücretli Otopark"))
        self.ucretsiz_buton.setText(_translate("MainWindow", "Ücretsiz Otopark"))
        self.doluluk.setText(_translate("MainWindow", "Doluluk Oranı"))
        self.arac_sayisi.setText(_translate("MainWindow", "Araç Sayısı"))
        self.ucret.setText(_translate("MainWindow", "<html><head/><body><p>Saatlik Ücret</p></body></html>"))
        self.guncelle_buton.setText(_translate("MainWindow", "Güncelle"))
        self.plaka.setText(_translate("MainWindow", "Plaka:"))
        self.pushButton.setText(_translate("MainWindow", "Ekle"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

